name: Continuous Integration

on:
  push:
    branches:
      - master

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    needs: [compile-release, tests, formatting, clippy]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Authenticate with Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build & Push Container Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          cache-from: type=registry,ref=ghcr.io/cwenck/deep-thought:latest-snapshot
          cache-to: type=inline
          tags: ghcr.io/cwenck/deep-thought:latest-snapshot
